volumes:
  toubeelib.db:
    driver: local

services:

  # service administration des bases de données
  adminer:
    image: adminer
    ports:
      - '8080:8080'

  # ===================GATEWAY================

  gateway:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '6081:80'
    volumes:
      - ./gateway/app/:/var/php/
    working_dir: /var/php
    command: php -S 0.0.0.0:80 -t /var/php/public

  # ==============TOUBEELIB================

  api.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib/toubeelib.env
    ports:
      - '6080:80'
    volumes:
      - ./toubeelib/app/:/var/php/
    working_dir: /var/php
    command: php -S 0.0.0.0:80 -t /var/php/public

  toubeelib.db:
    image: 'postgres:latest' 
    env_file: ./toubeelib/toubeelibdb.env
    ports:
      - '5432:5432'
    volumes:
      - ./toubeelib/sql/init-postgres:/docker-entrypoint-initdb.d
      - toubeelib.db:/var/lib/postgresql/data

  # ===================APP-PRATICIENS================

  app_praticiens:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    ports:
      - '6082:80'
    volumes:
      - ./app_praticiens/app/:/var/php/
    working_dir: /var/php
    command: php -S 0.0.0.0:80 -t /var/php/public